"""Build the reviewed, atomic SQL Editor bundle. Never connects to a database."""
from pathlib import Path
import hashlib
import re
import sys

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / 'docs/sql_database_catchup_20260928.sql'
VERSIONS = ['20260919000000', '20260920000000', '20260921000000',
            '20260921000001', '20260921000002', '20260923000000',
            '20260924000000', '20260927000000', '20260928000000']


def build():
    parts = ['''-- Generated by python scripts/build_db_catchup.py; do not edit this bundle.
-- Run the ENTIRE file as postgres in Supabase SQL Editor (project plitfdjzuealjxbylwxy).
-- Read docs/DATABASE_CATCHUP_20260928.md first. No auth passwords are changed.
-- One transaction: an error rolls back ALL changes. No migration history is fabricated.
BEGIN;
SET LOCAL lock_timeout = '10s';
SET LOCAL statement_timeout = '120s';
SET LOCAL datestyle = 'ISO, YMD';
SELECT pg_advisory_xact_lock(hashtextextended('ofc:database-catchup:20260928',0));
''']
    for version in VERSIONS:
        files = list((ROOT / 'supabase/migrations').glob(version + '_*.sql'))
        if len(files) != 1:
            raise ValueError(f'Expected one migration for {version}: {files}')
        source = files[0].read_text(encoding='utf-8')
        digest = hashlib.sha256(source.encode('utf-8')).hexdigest()
        # Only the OTP migration has transaction wrappers. PL/pgSQL BEGIN has no ;.
        source = re.sub(r'(?im)^(?:BEGIN|COMMIT);\s*$', '', source).strip()
        parts.append(f'-- SOURCE: {files[0].name}\n-- SHA256: {digest}\n{source}\n')
    parts.append((ROOT / 'docs/sql_database_catchup_checks.sql').read_text(encoding='utf-8'))
    parts.append("COMMIT;\nSELECT 'DATABASE_CATCHUP_OK' AS result;\n")
    return '\n'.join(parts)


if __name__ == '__main__':
    result = build()
    if '--check' in sys.argv:
        if not OUTPUT.exists() or OUTPUT.read_text(encoding='utf-8') != result:
            raise SystemExit('Bundle is stale: run python scripts/build_db_catchup.py')
        print('PASS SQL bundle matches source migrations')
    else:
        OUTPUT.write_text(result, encoding='utf-8', newline='\n')
        print(f'Generated {OUTPUT.relative_to(ROOT)} ({len(VERSIONS)} migrations)')
