-- Generated by python scripts/build_db_catchup.py; do not edit this bundle.
-- Run the ENTIRE file as postgres in Supabase SQL Editor (project plitfdjzuealjxbylwxy).
-- Read docs/DATABASE_CATCHUP_20260928.md first. No auth passwords are changed.
-- One transaction: an error rolls back ALL changes. No migration history is fabricated.
BEGIN;
SET LOCAL lock_timeout = '10s';
SET LOCAL statement_timeout = '120s';
SET LOCAL datestyle = 'ISO, YMD';
SELECT pg_advisory_xact_lock(hashtextextended('ofc:database-catchup:20260928',0));

-- SOURCE: 20260919000000_baseline_schema.sql
-- SHA256: f7aa0a2a80a88c62866877fed6540bf0c0c17f274c201c465434f0c1480e19d2
-- ==============================================================================
-- GS25 SCHEDULE APP — MASTER BASELINE SCHEMA MIGRATION
-- Migration Timestamp: 20260919000000
-- Idempotent script: Thích hợp chạy trên Supabase CLI hoặc SQL Editor.
-- ==============================================================================

-- 1. EXTENSIONS
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- 2. CORE TABLES
-- Bảng Cửa hàng (stores)
CREATE TABLE IF NOT EXISTS public.stores (
  id text PRIMARY KEY,
  name text NOT NULL,
  region text DEFAULT 'Hồ Chí Minh',
  sm_id text,
  is_active boolean NOT NULL DEFAULT true,
  staffing jsonb,
  demand jsonb,
  created_at timestamptz DEFAULT now()
);

-- Bảng Nhân viên (employees)
CREATE TABLE IF NOT EXISTS public.employees (
  id text PRIMARY KEY,
  name text NOT NULL,
  dept text NOT NULL,
  type text NOT NULL DEFAULT 'STFT',
  role text,
  job_title text,
  max_h numeric NOT NULL DEFAULT 48,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz DEFAULT now()
);

-- Bảng Phân quyền cửa hàng (user_store_roles)
CREATE TABLE IF NOT EXISTS public.user_store_roles (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_emp_id text NOT NULL REFERENCES public.employees(id) ON DELETE CASCADE,
  store_id text NOT NULL REFERENCES public.stores(id) ON DELETE CASCADE,
  app_role text NOT NULL DEFAULT 'employee',
  created_at timestamptz DEFAULT now(),
  UNIQUE(user_emp_id, store_id, app_role)
);

-- Bảng Lịch làm việc phân ca (schedules)
CREATE TABLE IF NOT EXISTS public.schedules (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  week_date text NOT NULL,
  emp_id text NOT NULL REFERENCES public.employees(id) ON DELETE CASCADE,
  shifts jsonb NOT NULL DEFAULT '{}'::jsonb,
  version int NOT NULL DEFAULT 1,
  updated_at timestamptz DEFAULT now(),
  CONSTRAINT uq_schedules_week_emp UNIQUE(week_date, emp_id)
);

-- Bảng Trạng thái tuần (schedule_weeks)
CREATE TABLE IF NOT EXISTS public.schedule_weeks (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  store_id text NOT NULL,
  week_date text NOT NULL,
  status text NOT NULL DEFAULT 'draft',
  submitted_by text,
  submitted_at timestamptz,
  reviewed_by text,
  reviewed_at timestamptz,
  review_note text,
  created_at timestamptz DEFAULT now(),
  UNIQUE(store_id, week_date)
);

-- Bảng Đơn xin đổi ca (shift_swaps)
CREATE TABLE IF NOT EXISTS public.shift_swaps (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  week_date text NOT NULL,
  store text NOT NULL,
  from_emp_id text NOT NULL REFERENCES public.employees(id),
  from_emp_name text,
  from_day text NOT NULL,
  from_shift text NOT NULL,
  to_emp_id text NOT NULL REFERENCES public.employees(id),
  to_emp_name text,
  to_day text NOT NULL,
  to_shift text NOT NULL,
  reason text,
  status text NOT NULL DEFAULT 'pending_partner',
  manager_note text,
  created_at timestamptz DEFAULT now(),
  resolved_at timestamptz
);

-- Bảng Khiếu nại / Bù công C&B (feedbacks)
CREATE TABLE IF NOT EXISTS public.feedbacks (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  emp_id text NOT NULL,
  emp_name text,
  dept text,
  emp_role text,
  emp_type text,
  date date,
  shift text,
  hours numeric,
  reason text,
  note text,
  image_url text,
  status text NOT NULL DEFAULT 'pending',
  resolution_note text,
  created_at timestamptz DEFAULT now()
);

-- Bảng Chấm công thực tế ezHR9 (attendance)
CREATE TABLE IF NOT EXISTS public.attendance (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  emp_id text NOT NULL REFERENCES public.employees(id),
  work_date date NOT NULL,
  actual_hours numeric NOT NULL DEFAULT 0,
  note text,
  updated_by text,
  updated_at timestamptz DEFAULT now(),
  UNIQUE(emp_id, work_date)
);

-- Bảng Kệ hàng (store_shelves)
CREATE TABLE IF NOT EXISTS public.store_shelves (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  store_id text NOT NULL,
  code text NOT NULL,
  name text,
  assignee_id text,
  notify_days int DEFAULT 3,
  due_date date,
  created_at timestamptz DEFAULT now(),
  UNIQUE(store_id, code)
);

-- Bảng Hàng hóa trên kệ (shelf_items)
CREATE TABLE IF NOT EXISTS public.shelf_items (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  shelf_id uuid NOT NULL REFERENCES public.store_shelves(id) ON DELETE CASCADE,
  store_id text NOT NULL,
  product_name text NOT NULL,
  sku text,
  qty numeric,
  expiry_date date,
  expiry_date_2 date,
  note text,
  updated_by text,
  updated_at timestamptz DEFAULT now()
);

-- 3. TỐI ƯU HÓA CHỈ MỤC HIỆU NĂNG CAO (INDEXES)
CREATE INDEX IF NOT EXISTS idx_employees_dept ON public.employees(dept);
CREATE INDEX IF NOT EXISTS idx_employees_is_active ON public.employees(is_active);
CREATE INDEX IF NOT EXISTS idx_employees_dept_active ON public.employees(dept, is_active);

CREATE INDEX IF NOT EXISTS idx_schedules_week_date ON public.schedules(week_date);
CREATE INDEX IF NOT EXISTS idx_schedules_emp_id ON public.schedules(emp_id);
CREATE INDEX IF NOT EXISTS idx_schedules_week_emp ON public.schedules(week_date, emp_id);

CREATE INDEX IF NOT EXISTS idx_schedule_weeks_week_date ON public.schedule_weeks(week_date DESC);
CREATE INDEX IF NOT EXISTS idx_schedule_weeks_store_week ON public.schedule_weeks(store_id, week_date);

CREATE INDEX IF NOT EXISTS idx_shift_swaps_store_created ON public.shift_swaps(store, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_shift_swaps_emp_from ON public.shift_swaps(from_emp_id);
CREATE INDEX IF NOT EXISTS idx_shift_swaps_emp_to ON public.shift_swaps(to_emp_id);

CREATE INDEX IF NOT EXISTS idx_feedbacks_dept_created ON public.feedbacks(dept, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_feedbacks_emp_created ON public.feedbacks(emp_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_attendance_range ON public.attendance(work_date, emp_id);
CREATE INDEX IF NOT EXISTS idx_attendance_emp_id ON public.attendance(emp_id);

CREATE INDEX IF NOT EXISTS idx_shelf_items_store ON public.shelf_items(store_id);
CREATE INDEX IF NOT EXISTS idx_shelf_items_shelf ON public.shelf_items(shelf_id);
CREATE INDEX IF NOT EXISTS idx_shelf_items_expiry ON public.shelf_items(expiry_date);

-- 4. BẬT ROW LEVEL SECURITY (RLS)
ALTER TABLE public.stores ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.employees ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.schedules ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.schedule_weeks ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.shift_swaps ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.feedbacks ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.attendance ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.store_shelves ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.shelf_items ENABLE ROW LEVEL SECURITY;

-- SOURCE: 20260920000000_auth_foundation.sql
-- SHA256: acd3077b936a73220b98d571eb42bf6acb792c1313f1855f0f526d02ffdb9787
-- Dependencies required by the 20260921 migrations on a clean installation.
-- Authorization is derived from server-owned employee records, never user_metadata.
CREATE TABLE IF NOT EXISTS public.app_profiles (
  id uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  emp_id text UNIQUE NOT NULL,
  display_name text,
  created_at timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE public.app_profiles ADD COLUMN IF NOT EXISTS credential_set_at timestamptz;
ALTER TABLE public.app_profiles ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN
  CREATE TYPE public.app_role AS ENUM ('ADMIN','AREA_MANAGER','STORE_MANAGER','FULL_TIME','PART_TIME','EMPLOYEE');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

CREATE OR REPLACE FUNCTION public.current_emp_id() RETURNS text
LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $$
  SELECT split_part(u.email, '@', 1) FROM auth.users u
  WHERE u.id = auth.uid() AND u.email LIKE '%@ofc.app'
    AND (u.email = 'admin@ofc.app' OR EXISTS (
      SELECT 1 FROM public.employees e WHERE e.id = split_part(u.email, '@', 1) AND e.is_active
    ));
$$;

CREATE OR REPLACE FUNCTION public.has_role(r public.app_role) RETURNS boolean
LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $$
  SELECT CASE WHEN r = 'ADMIN' THEN public.current_emp_id() = 'admin'
    ELSE EXISTS (SELECT 1 FROM public.employees e WHERE e.id = public.current_emp_id() AND e.is_active AND
      CASE r
        WHEN 'AREA_MANAGER' THEN
          upper(coalesce(e.role,'')) IN ('OFC','AM','AREA_MANAGER') OR upper(e.type) IN ('OFC','AM','AREA_MANAGER')
          OR upper(coalesce(e.job_title,'')) IN ('OFC','AM','AREA_MANAGER')
          OR concat_ws(' ', e.role, e.job_title) ILIKE '%khu vực%'
        WHEN 'STORE_MANAGER' THEN
          upper(coalesce(e.role,'')) IN ('SM','STORE_MANAGER') OR upper(e.type) IN ('SM','STORE_MANAGER')
          OR upper(coalesce(e.job_title,'')) IN ('SM','STORE_MANAGER')
          OR concat_ws(' ', e.role, e.job_title) ILIKE '%cửa hàng trưởng%'
          OR concat_ws(' ', e.role, e.job_title) ILIKE '%quản lý%'
        WHEN 'FULL_TIME' THEN upper(e.type) IN ('STFT','CSR_NEW','FULLTIME')
        WHEN 'PART_TIME' THEN upper(e.type) IN ('STPT','PARTTIME')
        WHEN 'EMPLOYEE' THEN true ELSE false END
    ) END;
$$;

CREATE OR REPLACE FUNCTION public.is_admin() RETURNS boolean
LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $$
  SELECT coalesce(public.current_emp_id() = 'admin', false);
$$;

CREATE OR REPLACE FUNCTION public.my_member_stores() RETURNS SETOF text
LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $$
  SELECT trim(d) FROM public.employees e, unnest(string_to_array(e.dept, ',')) d
  WHERE e.id = public.current_emp_id() AND e.is_active AND trim(d) <> '';
$$;

CREATE OR REPLACE FUNCTION public.my_managed_stores() RETURNS SETOF text
LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $$
  SELECT s.id FROM public.stores s WHERE public.is_admin() OR public.has_role('AREA_MANAGER')
    OR (public.has_role('STORE_MANAGER') AND s.id IN (SELECT public.my_member_stores()));
$$;

CREATE OR REPLACE FUNCTION public.dept_in_scope(p_dept text) RETURNS boolean
LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $$
  SELECT EXISTS (SELECT 1 FROM unnest(string_to_array(p_dept, ',')) d
    WHERE trim(d) IN (SELECT public.my_member_stores()) OR trim(d) IN (SELECT public.my_managed_stores()));
$$;

CREATE OR REPLACE FUNCTION public.can_manage_store(p_store text) RETURNS boolean
LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $$
  SELECT public.is_admin() OR p_store IN (SELECT public.my_managed_stores());
$$;

CREATE OR REPLACE FUNCTION public.ensure_app_profile_v2() RETURNS void
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE employee_id text := public.current_emp_id();
BEGIN
  IF employee_id IS NULL THEN RAISE EXCEPTION 'AUTH_REQUIRED'; END IF;
  INSERT INTO public.app_profiles(id, emp_id) VALUES(auth.uid(), employee_id)
    ON CONFLICT(id) DO UPDATE SET emp_id = excluded.emp_id;
END;
$$;

CREATE OR REPLACE FUNCTION public.login_lookup(p_ma text)
RETURNS TABLE (id text, name text, dept text, role text, type text, job_title text, max_h numeric, is_active boolean)
LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $$
  SELECT e.id,e.name,e.dept,e.role,e.type,e.job_title,e.max_h,e.is_active
  FROM public.employees e WHERE p_ma ~ '^\d{9}$' AND e.id = p_ma LIMIT 1;
$$;

-- Apply bounded policies even when legacy permissive policies exist. A restrictive
-- policy is ANDed with all permissive policies; old open_* rules cannot widen it.
CREATE OR REPLACE FUNCTION public.manages_employee(p_emp_id text) RETURNS boolean
LANGUAGE sql STABLE SECURITY DEFINER SET search_path=public AS $$
  SELECT public.is_admin() OR EXISTS (
    SELECT 1 FROM public.employees e, unnest(string_to_array(e.dept,',')) d
    WHERE e.id=p_emp_id AND public.can_manage_store(trim(d)));
$$;

DO $$
DECLARE t text; command text; predicate text; read_predicate text; write_predicate text;
BEGIN
  FOREACH t IN ARRAY ARRAY['stores','employees','attendance','feedbacks','shift_swaps','store_shelves','shelf_items','schedule_weeks'] LOOP
    read_predicate := CASE t
      WHEN 'stores' THEN 'public.current_emp_id() IS NOT NULL'
      -- The staff directory is shared for cross-store covering and shift requests.
      WHEN 'employees' THEN 'public.current_emp_id() IS NOT NULL'
      WHEN 'attendance' THEN 'emp_id=public.current_emp_id() OR public.manages_employee(emp_id)'
      WHEN 'feedbacks' THEN 'emp_id=public.current_emp_id() OR public.can_manage_store(dept)'
      WHEN 'shift_swaps' THEN 'from_emp_id=public.current_emp_id() OR to_emp_id=public.current_emp_id() OR public.can_manage_store(store)'
      WHEN 'store_shelves' THEN 'public.dept_in_scope(store_id)'
      WHEN 'shelf_items' THEN 'public.dept_in_scope(store_id)'
      WHEN 'schedule_weeks' THEN 'public.current_emp_id() IS NOT NULL' END;
    write_predicate := CASE t
      WHEN 'stores' THEN 'public.can_manage_store(id)'
      WHEN 'employees' THEN 'public.manages_employee(id)'
      WHEN 'attendance' THEN 'public.manages_employee(emp_id)'
      WHEN 'feedbacks' THEN 'public.can_manage_store(dept)'
      WHEN 'shift_swaps' THEN 'public.can_manage_store(store)'
      WHEN 'store_shelves' THEN 'public.can_manage_store(store_id)'
      WHEN 'shelf_items' THEN 'public.can_manage_store(store_id) OR EXISTS (SELECT 1 FROM public.store_shelves sh WHERE sh.id=shelf_id AND sh.store_id=shelf_items.store_id AND public.current_emp_id()=ANY(string_to_array(sh.assignee_id,'','')))'
      WHEN 'schedule_weeks' THEN 'public.can_manage_store(store_id)' END;
    FOREACH command IN ARRAY ARRAY['SELECT','INSERT','UPDATE','DELETE'] LOOP
      predicate := CASE WHEN command='SELECT' THEN read_predicate ELSE write_predicate END;
      IF t='stores' AND command IN ('INSERT','DELETE') THEN predicate:='public.is_admin()'; END IF;
      IF t='employees' AND command='INSERT' THEN predicate:='public.is_admin() OR EXISTS (SELECT 1 FROM unnest(string_to_array(dept,'','')) d WHERE public.can_manage_store(trim(d)))'; END IF;
      IF t='feedbacks' AND command='INSERT' THEN predicate:=predicate||' OR (emp_id=public.current_emp_id() AND status=''pending'' AND public.dept_in_scope(dept))'; END IF;
      IF t='shift_swaps' AND command='INSERT' THEN predicate:='from_emp_id=public.current_emp_id() AND status=''pending_partner'' AND public.dept_in_scope(store)'; END IF;
      IF t='shift_swaps' AND command='UPDATE' THEN predicate:=predicate||' OR from_emp_id=public.current_emp_id() OR to_emp_id=public.current_emp_id()'; END IF;
      IF t='shift_swaps' AND command='DELETE' THEN predicate:=predicate||' OR (from_emp_id=public.current_emp_id() AND status=''pending_partner'')'; END IF;
      predicate:='public.current_emp_id() IS NOT NULL AND ('||predicate||')';
      EXECUTE format('DROP POLICY IF EXISTS %I ON public.%I','stability_allow_'||lower(command),t);
      EXECUTE format('DROP POLICY IF EXISTS %I ON public.%I','stability_bound_'||lower(command),t);
      IF command='INSERT' THEN
        EXECUTE format('CREATE POLICY %I ON public.%I FOR INSERT TO authenticated WITH CHECK (%s)','stability_allow_insert',t,predicate);
        EXECUTE format('CREATE POLICY %I ON public.%I AS RESTRICTIVE FOR INSERT TO authenticated WITH CHECK (%s)','stability_bound_insert',t,predicate);
      ELSE
        EXECUTE format('CREATE POLICY %I ON public.%I FOR %s TO authenticated USING (%s)','stability_allow_'||lower(command),t,command,predicate);
        EXECUTE format('CREATE POLICY %I ON public.%I AS RESTRICTIVE FOR %s TO authenticated USING (%s)','stability_bound_'||lower(command),t,command,predicate);
      END IF;
    END LOOP;
  END LOOP;
END $$;

-- Manager appointments require Admin/AM; ordinary staff CRUD stays available to SM.
CREATE OR REPLACE FUNCTION public.employee_is_manager(p_role text,p_type text,p_title text) RETURNS boolean
LANGUAGE sql IMMUTABLE SET search_path=public AS $$
  SELECT upper(coalesce(p_role,'')) IN ('ADMIN','OFC','AM','AREA_MANAGER','SM','STORE_MANAGER')
    OR upper(coalesce(p_type,'')) IN ('ADMIN','OFC','AM','AREA_MANAGER','SM','STORE_MANAGER')
    OR upper(coalesce(p_title,'')) IN ('ADMIN','OFC','AM','AREA_MANAGER','SM','STORE_MANAGER')
    OR concat_ws(' ',p_role,p_title) ILIKE ANY(ARRAY['%quản lý%','%cửa hàng trưởng%','%khu vực%']);
$$;
CREATE OR REPLACE FUNCTION public.guard_employee_authority() RETURNS trigger
LANGUAGE plpgsql SECURITY INVOKER SET search_path=public AS $$
BEGIN
  IF current_user NOT IN ('authenticated','anon') THEN RETURN NEW; END IF;
  IF public.is_admin() OR public.has_role('AREA_MANAGER') THEN RETURN NEW; END IF;
  IF TG_OP='UPDATE' THEN
    IF NEW.id IS DISTINCT FROM OLD.id THEN RAISE EXCEPTION 'EMPLOYEE_ID_IMMUTABLE'; END IF;
    IF (NEW.role IS DISTINCT FROM OLD.role OR NEW.type IS DISTINCT FROM OLD.type
      OR NEW.job_title IS DISTINCT FROM OLD.job_title OR NEW.dept IS DISTINCT FROM OLD.dept
      OR NEW.is_active IS DISTINCT FROM OLD.is_active)
      AND (public.employee_is_manager(NEW.role,NEW.type,NEW.job_title)
        OR public.employee_is_manager(OLD.role,OLD.type,OLD.job_title)) THEN
      RAISE EXCEPTION 'AUTHORITY_FIELDS_REQUIRE_ADMIN_OR_AM';
    END IF;
  ELSIF public.employee_is_manager(NEW.role,NEW.type,NEW.job_title) THEN
    RAISE EXCEPTION 'AUTHORITY_FIELDS_REQUIRE_ADMIN_OR_AM';
  END IF;
  IF TG_OP='INSERT' OR NEW.dept IS DISTINCT FROM OLD.dept THEN
    IF EXISTS (SELECT 1 FROM unnest(string_to_array(NEW.dept,',')) d WHERE NOT public.can_manage_store(trim(d))) THEN
      RAISE EXCEPTION 'PERMISSION_DENIED';
    END IF;
  END IF;
  RETURN NEW;
END;
$$;
DROP TRIGGER IF EXISTS stability_employee_authority ON public.employees;
CREATE TRIGGER stability_employee_authority BEFORE INSERT OR UPDATE ON public.employees
  FOR EACH ROW EXECUTE FUNCTION public.guard_employee_authority();
ALTER TABLE public.user_store_roles ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.user_store_roles FROM anon, authenticated;

REVOKE ALL ON FUNCTION public.login_lookup(text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.login_lookup(text) TO anon, authenticated;
REVOKE ALL ON FUNCTION public.ensure_app_profile_v2() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.ensure_app_profile_v2() TO authenticated;
GRANT USAGE ON SCHEMA public TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.stores, public.employees, public.schedules,
  public.schedule_weeks, public.attendance, public.feedbacks, public.shift_swaps,
  public.store_shelves, public.shelf_items TO authenticated;

REVOKE ALL ON public.stores, public.employees, public.schedules, public.schedule_weeks,
  public.attendance, public.feedbacks, public.shift_swaps, public.store_shelves, public.shelf_items FROM anon;

-- SOURCE: 20260921000000_p03_custom_jwt_hook.sql
-- SHA256: cfc176c058d5e3e9825b7b89e5e168d323f35543c7e740631d522fb85a2074a8
-- Hook cho Supabase Custom Access Token (Khắc phục P0-3)
-- Tự động nhúng role thực tế từ CSDL vào JWT, bỏ qua metadata giả mạo từ client.

CREATE OR REPLACE FUNCTION public.custom_access_token_hook(event jsonb)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  claims jsonb;
  user_role text;
  user_dept text;
  emp_record record;
BEGIN
  -- Lấy claims hiện tại
  claims := event->'claims';

  -- Tìm nhân viên tương ứng với email
  SELECT id, role, type, dept INTO emp_record
  FROM public.employees
  WHERE id = REPLACE(REPLACE(claims->>'email', '@ofc.app', ''), 'admin', 'admin')
  LIMIT 1;

  IF FOUND THEN
    -- Ưu tiên role từ bảng employees thay vì metadata
    user_role := COALESCE(emp_record.role, emp_record.type, 'employee');
    user_dept := COALESCE(emp_record.dept, '');

    -- Ghi đè claims
    claims := jsonb_set(claims, '{app_role}', to_jsonb(user_role));
    claims := jsonb_set(claims, '{app_dept}', to_jsonb(user_dept));

    -- Trả về event đã sửa đổi
    event := jsonb_set(event, '{claims}', claims);
  END IF;

  RETURN event;
END;
$$;

-- Lưu ý: Phải vào Supabase Dashboard -> Authentication -> Hooks -> Enable Custom Access Token hook và chọn function này.

-- SOURCE: 20260921000001_p00_lock_schedule_weeks.sql
-- SHA256: c1e3263fc343df644fae5985b045cb49ad3643a8ae37ef382a24c2f3023419fd
-- Khắc phục P0: Khóa lịch ở backend
-- Cửa hàng trưởng (SM) chỉ có thể cập nhật/xóa/thêm lịch nếu schedule_weeks của tuần đó chưa bị khóa (draft hoặc rejected).
-- Nếu tuần đó đang pending hoặc approved, SM không thể sửa lịch nữa (Database level lock).

-- 1. Xóa policy cũ nếu có
DROP POLICY IF EXISTS p1_sch_sel ON public.schedules;
DROP POLICY IF EXISTS p1_sch_all ON public.schedules;
DROP POLICY IF EXISTS p1_sch_ins ON public.schedules;
DROP POLICY IF EXISTS p1_sch_upd ON public.schedules;
DROP POLICY IF EXISTS p1_sch_del ON public.schedules;

-- 2. Tạo hàm kiểm tra trạng thái khóa của tuần
CREATE OR REPLACE FUNCTION public.is_week_editable(p_store_id text, p_week_date text)
RETURNS boolean
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_status text;
BEGIN
  SELECT status INTO v_status
  FROM public.schedule_weeks
  WHERE store_id = p_store_id AND week_date = p_week_date;

  -- Nếu chưa có bản ghi (null) hoặc là draft, rejected thì cho phép sửa
  IF v_status IS NULL OR v_status IN ('draft', 'rejected') THEN
    return true;
  END IF;

  return false;
END;
$$;

-- 3. Tạo lại policy cho bảng schedules
-- Cho phép SELECT với tất cả mọi người
CREATE POLICY p1_sch_sel ON public.schedules FOR SELECT TO authenticated USING (true);

-- Cho phép ALL (Insert, Update, Delete)
CREATE POLICY p1_sch_all ON public.schedules FOR ALL TO authenticated
USING (
  public.is_admin()
  OR public.has_role('AREA_MANAGER')
  OR (
    public.has_role('STORE_MANAGER')
    AND exists(
      select 1 from public.employees e
      where e.id = schedules.emp_id and public.dept_in_scope(e.dept)
    )
    -- ĐIỀU KIỆN MỚI: Chỉ cho phép SM sửa nếu tuần chưa bị khóa
    AND public.is_week_editable(
      (select dept from public.employees e where e.id = schedules.emp_id limit 1),
      schedules.week_date
    )
  )
)
WITH CHECK (
  public.is_admin()
  OR public.has_role('AREA_MANAGER')
  OR (
    public.has_role('STORE_MANAGER')
    AND exists(
      select 1 from public.employees e
      where e.id = schedules.emp_id and public.dept_in_scope(e.dept)
    )
    -- ĐIỀU KIỆN MỚI: Chỉ cho phép SM sửa nếu tuần chưa bị khóa
    AND public.is_week_editable(
      (select dept from public.employees e where e.id = schedules.emp_id limit 1),
      schedules.week_date
    )
  )
);

-- SOURCE: 20260921000002_password_security_enhancement.sql
-- SHA256: f3be72ba28efc0cfa00073460bc1c8085c475697c6cae732ba2799f8ace7518a
-- Migration: 20260921000002_password_security_enhancement.sql
-- Thêm trường password_changed_at vào bảng employees để theo dõi trạng thái đổi mật khẩu
-- Hỗ trợ Admin giám sát ai đã đổi mật khẩu (xanh), ai còn dùng mật khẩu mặc định (đỏ), ai quá hạn

-- 1. Thêm cột password_changed_at và password_deadline vào employees nếu chưa có
ALTER TABLE public.employees ADD COLUMN IF NOT EXISTS password_changed_at timestamptz DEFAULT NULL;
ALTER TABLE public.employees ADD COLUMN IF NOT EXISTS password_deadline timestamptz DEFAULT NULL;

-- 2. Đồng bộ dữ liệu hiện có từ app_profiles nếu đã có thông tin credential_set_at
DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM information_schema.columns 
    WHERE table_schema = 'public' AND table_name = 'app_profiles' AND column_name = 'credential_set_at'
  ) THEN
    UPDATE public.employees e
    SET password_changed_at = p.credential_set_at
    FROM public.app_profiles p
    WHERE e.id = p.emp_id AND p.credential_set_at IS NOT NULL AND e.password_changed_at IS NULL;
  END IF;
END $$;

-- 3. Hàm cho phép nhân viên tự đánh dấu đã đổi mật khẩu (Security Definer)
CREATE OR REPLACE FUNCTION public.mark_my_password_changed()
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_emp_id text;
BEGIN
  v_emp_id := public.current_emp_id();
  IF v_emp_id IS NOT NULL THEN
    UPDATE public.employees SET password_changed_at = now() WHERE id = v_emp_id;
    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'app_profiles') THEN
      UPDATE public.app_profiles SET credential_set_at = now() WHERE emp_id = v_emp_id;
    END IF;
  END IF;
END;
$$;

GRANT EXECUTE ON FUNCTION public.mark_my_password_changed() TO authenticated;

-- 4. Hàm cho phép Admin/SM đặt lại cờ mật khẩu về NULL khi reset mật khẩu cho nhân viên
CREATE OR REPLACE FUNCTION public.admin_reset_employee_password_flag(p_emp_id text)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF public.is_admin() OR public.has_role('AREA_MANAGER') OR public.has_role('STORE_MANAGER') THEN
    UPDATE public.employees SET password_changed_at = NULL WHERE id = p_emp_id;
    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'app_profiles') THEN
      UPDATE public.app_profiles SET credential_set_at = NULL WHERE emp_id = p_emp_id;
    END IF;
  ELSE
    RAISE EXCEPTION 'Bạn không có quyền thực hiện thao tác này';
  END IF;
END;
$$;

GRANT EXECUTE ON FUNCTION public.admin_reset_employee_password_flag(text) TO authenticated;

-- SOURCE: 20260923000000_stability_transactions.sql
-- SHA256: 25ff7130ecfe1c6d97fc2f3ed94d051488875409423d51589359df7f3fb84ba5
-- Deploy before the frontend version that requires optimistic versions and atomic swaps.
ALTER TABLE public.schedules ADD COLUMN IF NOT EXISTS version integer NOT NULL DEFAULT 1;
ALTER TABLE public.schedules ADD COLUMN IF NOT EXISTS updated_by text;

-- Use the same workflow vocabulary as the app. Remove the old transition guard first.
DROP TRIGGER IF EXISTS trg_weeks_guard ON public.schedule_weeks;
ALTER TABLE public.schedule_weeks DROP CONSTRAINT IF EXISTS ck_weeks_status;
UPDATE public.schedule_weeks SET status='pending' WHERE status='submitted';
ALTER TABLE public.schedule_weeks ADD CONSTRAINT ck_weeks_status
  CHECK (status IN ('draft','pending','approved','rejected'));

CREATE OR REPLACE FUNCTION public.weeks_guard() RETURNS trigger
LANGUAGE plpgsql SECURITY INVOKER SET search_path=public AS $$
BEGIN
  PERFORM pg_advisory_xact_lock(hashtextextended('week:'||NEW.store_id||':'||NEW.week_date,0));
  -- ON CONFLICT runs INSERT triggers before UPDATE triggers. Validate the existing
  -- row transition in the UPDATE branch, while keeping its row locked.
  IF TG_OP='INSERT' THEN
    PERFORM 1 FROM public.schedule_weeks WHERE store_id=NEW.store_id AND week_date=NEW.week_date FOR UPDATE;
    IF FOUND THEN RETURN NEW; END IF;
  END IF;
  IF NOT public.can_manage_store(NEW.store_id) THEN RAISE EXCEPTION 'PERMISSION_DENIED'; END IF;
  IF TG_OP='UPDATE' AND (NEW.store_id IS DISTINCT FROM OLD.store_id OR NEW.week_date IS DISTINCT FROM OLD.week_date) THEN
    RAISE EXCEPTION 'WEEK_ID_IMMUTABLE';
  END IF;
  IF TG_OP='UPDATE' AND NEW.status=OLD.status THEN RETURN NEW; END IF;
  IF NEW.status IN ('approved','rejected') AND NOT (public.is_admin() OR public.has_role('AREA_MANAGER')) THEN
    RAISE EXCEPTION 'PERMISSION_DENIED: Only AM/admin can review';
  END IF;
  IF TG_OP='INSERT' THEN
    IF NEW.status NOT IN ('draft','pending') THEN RAISE EXCEPTION 'INVALID_TRANSITION'; END IF;
  ELSIF NOT (
    (OLD.status IN ('draft','rejected') AND NEW.status='pending') OR
    (OLD.status='pending' AND NEW.status IN ('approved','rejected')) OR
    (OLD.status='approved' AND NEW.status='rejected') OR
    (OLD.status='rejected' AND NEW.status='draft')
  ) THEN RAISE EXCEPTION 'INVALID_TRANSITION: % -> %', OLD.status, NEW.status; END IF;
  IF NEW.status='pending' THEN NEW.submitted_by:=public.current_emp_id(); NEW.submitted_at:=now(); END IF;
  IF NEW.status IN ('approved','rejected') THEN NEW.reviewed_by:=public.current_emp_id(); NEW.reviewed_at:=now(); END IF;
  RETURN NEW;
END;
$$;
CREATE TRIGGER trg_weeks_guard BEFORE INSERT OR UPDATE ON public.schedule_weeks
  FOR EACH ROW EXECUTE FUNCTION public.weeks_guard();

-- Employees may register their own shifts; management remains scoped to owned stores.
DROP POLICY IF EXISTS p1_sch_all ON public.schedules;
CREATE POLICY p1_sch_all ON public.schedules FOR ALL TO authenticated
  USING (public.current_emp_id() IS NOT NULL AND (
    emp_id=public.current_emp_id() OR public.is_admin() OR EXISTS (
      SELECT 1 FROM public.employees e, unnest(string_to_array(e.dept,',')) d
      WHERE e.id=emp_id AND public.can_manage_store(trim(d))
    )))
  WITH CHECK (public.current_emp_id() IS NOT NULL AND (
    emp_id=public.current_emp_id() OR public.is_admin() OR EXISTS (
      SELECT 1 FROM public.employees e, unnest(string_to_array(e.dept,',')) d
      WHERE e.id=emp_id AND public.can_manage_store(trim(d))
    )));

-- Applies even to callers bypassing the RPC, and to both home and covering stores.
CREATE OR REPLACE FUNCTION public.guard_schedule_lock() RETURNS trigger
LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$
DECLARE row_emp text; row_week text; row_shifts jsonb; old_shifts jsonb:='{}'; home_dept text; target text;
BEGIN
  IF TG_OP='DELETE' THEN row_emp:=OLD.emp_id; row_week:=OLD.week_date; row_shifts:=OLD.shifts;
  ELSE row_emp:=NEW.emp_id; row_week:=NEW.week_date; row_shifts:=NEW.shifts; END IF;
  IF TG_OP='UPDATE' THEN
    IF NEW.emp_id IS DISTINCT FROM OLD.emp_id OR NEW.week_date IS DISTINCT FROM OLD.week_date THEN
      RAISE EXCEPTION 'SCHEDULE_ID_IMMUTABLE';
    END IF;
    old_shifts:=OLD.shifts;
  END IF;
  SELECT dept INTO home_dept FROM public.employees WHERE id=row_emp;
  FOR target IN
    SELECT trim(d) FROM unnest(string_to_array(home_dept,',')) d
    UNION
    SELECT CASE WHEN jsonb_typeof(value)='object' THEN value->>'covering_store'
      WHEN jsonb_typeof(value)='string' AND value#>>'{}' LIKE '%\_%' ESCAPE '\'
        THEN split_part(value#>>'{}','_',2) END
    FROM (SELECT value FROM jsonb_each(row_shifts) UNION ALL SELECT value FROM jsonb_each(old_shifts)) cells
    ORDER BY 1
  LOOP
    IF target IS NULL OR target='' THEN CONTINUE; END IF;
    PERFORM pg_advisory_xact_lock(hashtextextended('week:'||target||':'||row_week,0));
    IF NOT public.is_week_editable(target,row_week) THEN RAISE EXCEPTION 'WEEK_LOCKED'; END IF;
  END LOOP;
  IF TG_OP='DELETE' THEN RETURN OLD; END IF;
  RETURN NEW;
END;
$$;
DROP TRIGGER IF EXISTS stability_schedule_lock ON public.schedules;
CREATE TRIGGER stability_schedule_lock BEFORE INSERT OR UPDATE OR DELETE ON public.schedules
  FOR EACH ROW EXECUTE FUNCTION public.guard_schedule_lock();

-- Remove the obsolete three-argument overload to avoid PostgREST ambiguity.
DROP FUNCTION IF EXISTS public.save_employee_schedule(text,text,jsonb);
CREATE OR REPLACE FUNCTION public.save_employee_schedule(
  p_week_date text, p_emp_id text, p_shifts jsonb, p_expect_version integer DEFAULT NULL
) RETURNS integer LANGUAGE plpgsql SECURITY INVOKER SET search_path=public AS $$
DECLARE current_version integer; next_version integer;
BEGIN
  IF auth.uid() IS NULL THEN RAISE EXCEPTION 'AUTH_REQUIRED'; END IF;
  IF p_expect_version IS NULL OR p_expect_version < 0 THEN RAISE EXCEPTION 'EXPECTED_VERSION_REQUIRED'; END IF;
  IF p_week_date !~ '^\d{4}-\d{2}-\d{2}$' OR extract(isodow FROM p_week_date::date)<>1 THEN
    RAISE EXCEPTION 'INVALID_WEEK';
  END IF;
  IF jsonb_typeof(p_shifts) IS DISTINCT FROM 'object' THEN RAISE EXCEPTION 'INVALID_SHIFTS'; END IF;
  -- Also locks creation of a currently missing row, which SELECT FOR UPDATE cannot do.
  PERFORM pg_advisory_xact_lock(hashtextextended(p_week_date||':'||p_emp_id,0));
  SELECT version INTO current_version FROM public.schedules WHERE week_date=p_week_date AND emp_id=p_emp_id FOR UPDATE;
  IF coalesce(current_version,0)<>p_expect_version THEN
    RAISE EXCEPTION 'CONFLICT: schedule changed' USING ERRCODE='40001';
  END IF;
  IF current_version IS NULL THEN
    INSERT INTO public.schedules(week_date,emp_id,shifts,version,updated_by)
      VALUES(p_week_date,p_emp_id,p_shifts,1,public.current_emp_id()) RETURNING version INTO next_version;
  ELSE
    UPDATE public.schedules SET shifts=p_shifts,version=version+1,updated_at=now(),updated_by=public.current_emp_id()
      WHERE week_date=p_week_date AND emp_id=p_emp_id RETURNING version INTO next_version;
    IF NOT FOUND THEN RAISE EXCEPTION 'PERMISSION_DENIED'; END IF;
  END IF;
  RETURN next_version;
END;
$$;

CREATE OR REPLACE FUNCTION public.upsert_schedules_bulk(p_rows jsonb)
RETURNS TABLE(o_emp_id text,o_week_date text,o_version integer)
LANGUAGE plpgsql SECURITY INVOKER SET search_path=public AS $$
DECLARE r record;
BEGIN
  IF jsonb_typeof(p_rows) IS DISTINCT FROM 'array' THEN RAISE EXCEPTION 'INVALID_ROWS'; END IF;
  FOR r IN SELECT * FROM jsonb_to_recordset(p_rows)
    AS x(week_date text,emp_id text,shifts jsonb,expect_version integer) ORDER BY week_date,emp_id LOOP
    o_version:=public.save_employee_schedule(r.week_date,r.emp_id,r.shifts,r.expect_version);
    o_emp_id:=r.emp_id; o_week_date:=r.week_date; RETURN NEXT;
  END LOOP;
END;
$$;

CREATE OR REPLACE FUNCTION public.approve_shift_swap_atomic_v2(p_swap_id uuid,p_manager_note text DEFAULT NULL)
RETURNS boolean LANGUAGE plpgsql SECURITY INVOKER SET search_path=public AS $$
DECLARE s public.shift_swaps%ROWTYPE;
BEGIN
  SELECT * INTO s FROM public.shift_swaps WHERE id=p_swap_id FOR UPDATE;
  IF NOT FOUND THEN RAISE EXCEPTION 'SWAP_NOT_FOUND'; END IF;
  IF NOT public.can_manage_store(s.store) THEN RAISE EXCEPTION 'PERMISSION_DENIED'; END IF;
  IF s.status='approved' THEN RETURN true; END IF;
  UPDATE public.shift_swaps SET status='approved',manager_note=coalesce(p_manager_note,manager_note),resolved_at=now()
    WHERE id=p_swap_id;
  IF NOT FOUND THEN RAISE EXCEPTION 'PERMISSION_DENIED'; END IF;
  RETURN true;
END;
$$;

-- Stop participants from self-approving through direct UPDATE.
CREATE OR REPLACE FUNCTION public.guard_swap_transition() RETURNS trigger
LANGUAGE plpgsql SECURITY INVOKER SET search_path=public AS $$
DECLARE s public.shift_swaps%ROWTYPE; a jsonb; b jsonb; a_new jsonb; b_new jsonb;
  av integer; bv integer; employee_id text;
BEGIN
  IF NEW.from_emp_id<>OLD.from_emp_id OR NEW.to_emp_id<>OLD.to_emp_id OR NEW.week_date<>OLD.week_date
    OR NEW.store<>OLD.store OR NEW.from_day<>OLD.from_day OR NEW.to_day<>OLD.to_day
    OR NEW.from_shift<>OLD.from_shift OR NEW.to_shift<>OLD.to_shift THEN RAISE EXCEPTION 'SWAP_IMMUTABLE'; END IF;
  IF NEW.status=OLD.status THEN RETURN NEW; END IF;
  IF OLD.status IN ('approved','rejected','cancelled') THEN RAISE EXCEPTION 'INVALID_TRANSITION'; END IF;
  IF NEW.status IN ('approved','rejected') AND NOT public.can_manage_store(OLD.store) THEN RAISE EXCEPTION 'PERMISSION_DENIED'; END IF;
  IF NEW.status='approved' AND OLD.status<>'pending_manager' THEN RAISE EXCEPTION 'INVALID_TRANSITION'; END IF;
  IF NEW.status='pending_manager' AND (OLD.status<>'pending_partner' OR NOT (OLD.to_emp_id=public.current_emp_id() OR public.can_manage_store(OLD.store))) THEN RAISE EXCEPTION 'PERMISSION_DENIED'; END IF;
  IF NEW.status='cancelled' AND NOT (OLD.from_emp_id=public.current_emp_id() OR public.can_manage_store(OLD.store)) THEN RAISE EXCEPTION 'PERMISSION_DENIED'; END IF;
  IF NEW.status NOT IN ('approved','rejected','cancelled','pending_manager') THEN RAISE EXCEPTION 'INVALID_TRANSITION'; END IF;
  IF NEW.status='approved' THEN
    s:=OLD;
  IF s.status<>'pending_manager' OR s.from_emp_id=s.to_emp_id THEN RAISE EXCEPTION 'INVALID_SWAP_STATUS'; END IF;
  IF s.from_day NOT IN ('T2','T3','T4','T5','T6','T7','CN') OR s.to_day NOT IN ('T2','T3','T4','T5','T6','T7','CN') THEN
    RAISE EXCEPTION 'INVALID_DAY';
  END IF;
  FOR employee_id IN SELECT unnest(ARRAY[s.from_emp_id,s.to_emp_id]) ORDER BY 1 LOOP
    PERFORM pg_advisory_xact_lock(hashtextextended(s.week_date||':'||employee_id,0));
  END LOOP;
  SELECT shifts,version INTO a,av FROM public.schedules WHERE week_date=s.week_date AND emp_id=s.from_emp_id FOR UPDATE;
  SELECT shifts,version INTO b,bv FROM public.schedules WHERE week_date=s.week_date AND emp_id=s.to_emp_id FOR UPDATE;
  IF a IS NULL OR b IS NULL THEN RAISE EXCEPTION 'SCHEDULE_NOT_FOUND'; END IF;
  -- Compare the requested shifts with current data before applying an old request.
  IF lower(split_part(coalesce(a->s.from_day->>'shift',a->>s.from_day,''),'_',1))<>lower(s.from_shift)
    OR lower(split_part(coalesce(b->s.to_day->>'shift',b->>s.to_day,''),'_',1))<>lower(s.to_shift) THEN
    RAISE EXCEPTION 'CONFLICT: requested shifts changed' USING ERRCODE='40001';
  END IF;
  a_new:=jsonb_set(a,ARRAY[s.from_day],coalesce(b->s.from_day,'""'::jsonb),true);
  b_new:=jsonb_set(b,ARRAY[s.from_day],coalesce(a->s.from_day,'""'::jsonb),true);
  IF s.from_day<>s.to_day THEN
    a_new:=jsonb_set(a_new,ARRAY[s.to_day],coalesce(b->s.to_day,'""'::jsonb),true);
    b_new:=jsonb_set(b_new,ARRAY[s.to_day],coalesce(a->s.to_day,'""'::jsonb),true);
  END IF;
  PERFORM public.save_employee_schedule(s.week_date,s.from_emp_id,a_new,av);
  PERFORM public.save_employee_schedule(s.week_date,s.to_emp_id,b_new,bv);
    NEW.resolved_at:=now();
  END IF;
  RETURN NEW;
END;
$$;
DROP TRIGGER IF EXISTS stability_swap_transition ON public.shift_swaps;
CREATE TRIGGER stability_swap_transition BEFORE UPDATE ON public.shift_swaps
  FOR EACH ROW EXECUTE FUNCTION public.guard_swap_transition();

-- Removing an attendance override must be permitted for its managing stores.
DROP POLICY IF EXISTS stability_attendance_delete ON public.attendance;
CREATE POLICY stability_attendance_delete ON public.attendance FOR DELETE TO authenticated USING (
  EXISTS (SELECT 1 FROM public.employees e, unnest(string_to_array(e.dept,',')) d
    WHERE e.id=emp_id AND public.can_manage_store(trim(d)))
);

REVOKE ALL ON FUNCTION public.save_employee_schedule(text,text,jsonb,integer),
  public.upsert_schedules_bulk(jsonb), public.approve_shift_swap_atomic_v2(uuid,text) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.save_employee_schedule(text,text,jsonb,integer),
  public.upsert_schedules_bulk(jsonb), public.approve_shift_swap_atomic_v2(uuid,text) TO authenticated;

-- Restrict a legacy broad SELECT to signed-in, active app identities.
DROP POLICY IF EXISTS stability_schedule_identity ON public.schedules;
CREATE POLICY stability_schedule_identity ON public.schedules AS RESTRICTIVE FOR ALL TO authenticated
  USING (public.current_emp_id() IS NOT NULL) WITH CHECK (public.current_emp_id() IS NOT NULL);
CREATE OR REPLACE FUNCTION public.admin_reset_employee_password_flag(p_emp_id text)
RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$
BEGIN
  IF NOT public.manages_employee(p_emp_id) THEN RAISE EXCEPTION 'PERMISSION_DENIED'; END IF;
  UPDATE public.employees SET password_changed_at=NULL WHERE id=p_emp_id;
  UPDATE public.app_profiles SET credential_set_at=NULL WHERE emp_id=p_emp_id;
END;
$$;
REVOKE ALL ON FUNCTION public.admin_reset_employee_password_flag(text), public.mark_my_password_changed() FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.admin_reset_employee_password_flag(text), public.mark_my_password_changed() TO authenticated;

DO $$ DECLARE cmd text; predicate text:='emp_id=public.current_emp_id() OR public.manages_employee(emp_id)';
BEGIN
  FOREACH cmd IN ARRAY ARRAY['INSERT','UPDATE','DELETE'] LOOP
    EXECUTE format('DROP POLICY IF EXISTS %I ON public.schedules','stability_bound_'||lower(cmd));
    IF cmd='INSERT' THEN
      EXECUTE format('CREATE POLICY stability_bound_insert ON public.schedules AS RESTRICTIVE FOR INSERT TO authenticated WITH CHECK (%s)',predicate);
    ELSE
      EXECUTE format('CREATE POLICY %I ON public.schedules AS RESTRICTIVE FOR %s TO authenticated USING (%s)','stability_bound_'||lower(cmd),cmd,predicate);
    END IF;
  END LOOP;
END $$;

-- Versioned lookup avoids changing the result type of an existing login_lookup.
CREATE OR REPLACE FUNCTION public.login_lookup_v2(p_ma text)
RETURNS TABLE(id text,name text,dept text,role text,type text,job_title text,max_h numeric,is_active boolean,
  created_at timestamptz,password_changed_at timestamptz,password_deadline timestamptz)
LANGUAGE sql STABLE SECURITY DEFINER SET search_path=public AS $$
  SELECT e.id,e.name,e.dept,e.role,e.type,e.job_title,e.max_h,e.is_active,
    e.created_at,e.password_changed_at,e.password_deadline FROM public.employees e
  WHERE p_ma ~ '^\d{9}$' AND e.id=p_ma LIMIT 1;
$$;
REVOKE ALL ON FUNCTION public.login_lookup_v2(text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.login_lookup_v2(text) TO anon,authenticated;

CREATE OR REPLACE FUNCTION public.guard_week_delete() RETURNS trigger
LANGUAGE plpgsql SECURITY INVOKER SET search_path=public AS $$
BEGIN
  PERFORM pg_advisory_xact_lock(hashtextextended('week:'||OLD.store_id||':'||OLD.week_date,0));
  IF OLD.status IN ('pending','approved') THEN RAISE EXCEPTION 'WEEK_LOCKED'; END IF;
  RETURN OLD;
END;
$$;
DROP TRIGGER IF EXISTS stability_week_delete ON public.schedule_weeks;
CREATE TRIGGER stability_week_delete BEFORE DELETE ON public.schedule_weeks
  FOR EACH ROW EXECUTE FUNCTION public.guard_week_delete();

-- A resolution with a corrected shift must either commit both changes or neither.
CREATE OR REPLACE FUNCTION public.resolve_feedback_atomic_v2(
  p_feedback_id uuid,p_status text,p_resolution_note text DEFAULT '',p_schedule jsonb DEFAULT NULL
) RETURNS jsonb LANGUAGE plpgsql SECURITY INVOKER SET search_path=public AS $$
DECLARE f public.feedbacks%ROWTYPE; schedule_row public.schedules%ROWTYPE;
  week_key text; day_key text; new_version integer; next_shifts jsonb; result jsonb:=NULL;
BEGIN
  SELECT * INTO f FROM public.feedbacks WHERE id=p_feedback_id FOR UPDATE;
  IF NOT FOUND THEN RAISE EXCEPTION 'FEEDBACK_NOT_FOUND'; END IF;
  IF NOT coalesce(public.can_manage_store(f.dept),false) OR f.emp_id=public.current_emp_id() THEN
    RAISE EXCEPTION 'PERMISSION_DENIED';
  END IF;
  IF p_status IS NULL OR p_status NOT IN ('approved','rejected') THEN RAISE EXCEPTION 'INVALID_STATUS'; END IF;
  IF f.status NOT IN ('pending',p_status) THEN RAISE EXCEPTION 'INVALID_TRANSITION'; END IF;
  IF p_schedule IS NOT NULL THEN
    IF p_status<>'approved' OR jsonb_typeof(p_schedule) IS DISTINCT FROM 'object'
      OR p_schedule->>'empId' IS DISTINCT FROM f.emp_id THEN RAISE EXCEPTION 'INVALID_CORRECTION'; END IF;
    week_key:=p_schedule->>'week'; day_key:=p_schedule->>'day';
    IF week_key IS NULL OR day_key IS NULL OR day_key NOT IN ('T2','T3','T4','T5','T6','T7','CN')
      OR NOT p_schedule ? 'shiftCode' THEN RAISE EXCEPTION 'INVALID_CORRECTION'; END IF;
    PERFORM pg_advisory_xact_lock(hashtextextended(week_key||':'||f.emp_id,0));
    SELECT * INTO schedule_row FROM public.schedules WHERE week_date=week_key AND emp_id=f.emp_id FOR UPDATE;
    IF f.status='pending' THEN
      next_shifts:=jsonb_set(coalesce(schedule_row.shifts,'{}'::jsonb),ARRAY[day_key],p_schedule->'shiftCode',true);
      new_version:=public.save_employee_schedule(week_key,f.emp_id,next_shifts,(p_schedule->>'expect_version')::integer);
    ELSE
      next_shifts:=schedule_row.shifts; new_version:=schedule_row.version;
    END IF;
    result:=jsonb_build_object('emp_id',f.emp_id,'week_date',week_key,'shifts',next_shifts,'version',new_version);
  END IF;
  IF f.status='pending' THEN
    UPDATE public.feedbacks SET status=p_status,resolution_note=p_resolution_note WHERE id=p_feedback_id;
    IF NOT FOUND THEN RAISE EXCEPTION 'PERMISSION_DENIED'; END IF;
  END IF;
  RETURN result;
END;
$$;
REVOKE ALL ON FUNCTION public.resolve_feedback_atomic_v2(uuid,text,text,jsonb) FROM PUBLIC,anon;
GRANT EXECUTE ON FUNCTION public.resolve_feedback_atomic_v2(uuid,text,text,jsonb) TO authenticated;

DROP POLICY IF EXISTS stability_feedback_resolution ON public.feedbacks;
CREATE POLICY stability_feedback_resolution ON public.feedbacks AS RESTRICTIVE FOR UPDATE TO authenticated
  USING (emp_id<>public.current_emp_id()) WITH CHECK (emp_id<>public.current_emp_id());
DROP POLICY IF EXISTS stability_feedback_initial_status ON public.feedbacks;
CREATE POLICY stability_feedback_initial_status ON public.feedbacks AS RESTRICTIVE FOR INSERT TO authenticated
  WITH CHECK (status='pending');

-- SOURCE: 20260924000000_jev_decisions.sql
-- SHA256: a62f9d75494eb7fed16887d7ddfe5e2229870fb688a894c8f1697d841bb948ec
-- Jev automation: service-only commit with canonical snapshot verification.
CREATE TABLE IF NOT EXISTS public.jev_auto_approval_settings (
  store_id text PRIMARY KEY REFERENCES public.stores(id), enabled boolean NOT NULL DEFAULT false,
  min_noul numeric NOT NULL CHECK (min_noul BETWEEN 0.9 AND 1),
  min_confidence numeric NOT NULL CHECK (min_confidence BETWEEN 0.9 AND 1),
  model text NOT NULL, calibrated_at timestamptz NOT NULL
);
CREATE TABLE IF NOT EXISTS public.jev_decisions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(), task text NOT NULL, user_id uuid,
  latency_ms integer, ok boolean NOT NULL, fail_reason text, model text,
  answers jsonb, auto_approved boolean NOT NULL DEFAULT false, created_at timestamptz DEFAULT now()
);
ALTER TABLE public.jev_auto_approval_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.jev_decisions ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.jev_auto_approval_settings, public.jev_decisions FROM anon, authenticated;
GRANT ALL ON public.jev_auto_approval_settings, public.jev_decisions TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.schedules, public.shift_swaps TO service_role;
GRANT SELECT, UPDATE ON public.employees TO service_role;
CREATE OR REPLACE FUNCTION public.save_employee_schedule(
  p_week_date text, p_emp_id text, p_shifts jsonb, p_expect_version integer DEFAULT NULL
) RETURNS integer LANGUAGE plpgsql SECURITY INVOKER SET search_path=public AS $$
DECLARE current_version integer; next_version integer;
BEGIN
  IF auth.uid() IS NULL AND current_user <> 'service_role' THEN RAISE EXCEPTION 'AUTH_REQUIRED'; END IF;
  IF p_expect_version IS NULL OR p_expect_version < 0 THEN RAISE EXCEPTION 'EXPECTED_VERSION_REQUIRED'; END IF;
  IF p_week_date !~ '^\d{4}-\d{2}-\d{2}$' OR extract(isodow FROM p_week_date::date)<>1 THEN
    RAISE EXCEPTION 'INVALID_WEEK';
  END IF;
  IF jsonb_typeof(p_shifts) IS DISTINCT FROM 'object' THEN RAISE EXCEPTION 'INVALID_SHIFTS'; END IF;
  -- Also locks creation of a currently missing row, which SELECT FOR UPDATE cannot do.
  PERFORM pg_advisory_xact_lock(hashtextextended(p_week_date||':'||p_emp_id,0));
  SELECT version INTO current_version FROM public.schedules WHERE week_date=p_week_date AND emp_id=p_emp_id FOR UPDATE;
  IF coalesce(current_version,0)<>p_expect_version THEN
    RAISE EXCEPTION 'CONFLICT: schedule changed' USING ERRCODE='40001';
  END IF;
  IF current_version IS NULL THEN
    INSERT INTO public.schedules(week_date,emp_id,shifts,version,updated_by)
      VALUES(p_week_date,p_emp_id,p_shifts,1,public.current_emp_id()) RETURNING version INTO next_version;
  ELSE
    UPDATE public.schedules SET shifts=p_shifts,version=version+1,updated_at=now(),updated_by=public.current_emp_id()
      WHERE week_date=p_week_date AND emp_id=p_emp_id RETURNING version INTO next_version;
    IF NOT FOUND THEN RAISE EXCEPTION 'PERMISSION_DENIED'; END IF;
  END IF;
  RETURN next_version;
END;
$$;

CREATE OR REPLACE FUNCTION public.approve_shift_swap_atomic_v2(p_swap_id uuid,p_manager_note text DEFAULT NULL)
RETURNS boolean LANGUAGE plpgsql SECURITY INVOKER SET search_path=public AS $$
DECLARE s public.shift_swaps%ROWTYPE;
BEGIN
  SELECT * INTO s FROM public.shift_swaps WHERE id=p_swap_id FOR UPDATE;
  IF NOT FOUND THEN RAISE EXCEPTION 'SWAP_NOT_FOUND'; END IF;
  IF NOT public.can_manage_store(s.store) AND current_user <> 'service_role' THEN RAISE EXCEPTION 'PERMISSION_DENIED'; END IF;
  IF s.status='approved' THEN RETURN true; END IF;
  UPDATE public.shift_swaps SET status='approved',manager_note=coalesce(p_manager_note,manager_note),resolved_at=now()
    WHERE id=p_swap_id;
  IF NOT FOUND THEN RAISE EXCEPTION 'PERMISSION_DENIED'; END IF;
  RETURN true;
END;
$$;

-- Stop participants from self-approving through direct UPDATE.
CREATE OR REPLACE FUNCTION public.guard_swap_transition() RETURNS trigger
LANGUAGE plpgsql SECURITY INVOKER SET search_path=public AS $$
DECLARE s public.shift_swaps%ROWTYPE; a jsonb; b jsonb; a_new jsonb; b_new jsonb;
  av integer; bv integer; employee_id text;
BEGIN
  IF NEW.from_emp_id<>OLD.from_emp_id OR NEW.to_emp_id<>OLD.to_emp_id OR NEW.week_date<>OLD.week_date
    OR NEW.store<>OLD.store OR NEW.from_day<>OLD.from_day OR NEW.to_day<>OLD.to_day
    OR NEW.from_shift<>OLD.from_shift OR NEW.to_shift<>OLD.to_shift THEN RAISE EXCEPTION 'SWAP_IMMUTABLE'; END IF;
  IF NEW.status=OLD.status THEN RETURN NEW; END IF;
  IF OLD.status IN ('approved','rejected','cancelled') THEN RAISE EXCEPTION 'INVALID_TRANSITION'; END IF;
  IF NEW.status='approved' AND NOT public.can_manage_store(OLD.store) AND current_user <> 'service_role' THEN RAISE EXCEPTION 'PERMISSION_DENIED'; END IF;
  IF NEW.status='rejected' AND NOT public.can_manage_store(OLD.store)
    AND NOT (OLD.status='pending_partner' AND OLD.to_emp_id=public.current_emp_id()) THEN RAISE EXCEPTION 'PERMISSION_DENIED'; END IF;
  IF NEW.status='approved' AND OLD.status<>'pending_manager' THEN RAISE EXCEPTION 'INVALID_TRANSITION'; END IF;
  IF NEW.status='pending_manager' AND (OLD.status<>'pending_partner' OR NOT (OLD.to_emp_id=public.current_emp_id() OR public.can_manage_store(OLD.store))) THEN RAISE EXCEPTION 'PERMISSION_DENIED'; END IF;
  IF NEW.status='cancelled' AND NOT (OLD.from_emp_id=public.current_emp_id() OR public.can_manage_store(OLD.store)) THEN RAISE EXCEPTION 'PERMISSION_DENIED'; END IF;
  IF NEW.status NOT IN ('approved','rejected','cancelled','pending_manager') THEN RAISE EXCEPTION 'INVALID_TRANSITION'; END IF;
  IF NEW.status='approved' THEN
    s:=OLD;
  IF s.status<>'pending_manager' OR s.from_emp_id=s.to_emp_id THEN RAISE EXCEPTION 'INVALID_SWAP_STATUS'; END IF;
  IF s.from_day NOT IN ('T2','T3','T4','T5','T6','T7','CN') OR s.to_day NOT IN ('T2','T3','T4','T5','T6','T7','CN') THEN
    RAISE EXCEPTION 'INVALID_DAY';
  END IF;
  FOR employee_id IN SELECT unnest(ARRAY[s.from_emp_id,s.to_emp_id]) ORDER BY 1 LOOP
    PERFORM pg_advisory_xact_lock(hashtextextended(s.week_date||':'||employee_id,0));
  END LOOP;
  SELECT shifts,version INTO a,av FROM public.schedules WHERE week_date=s.week_date AND emp_id=s.from_emp_id FOR UPDATE;
  SELECT shifts,version INTO b,bv FROM public.schedules WHERE week_date=s.week_date AND emp_id=s.to_emp_id FOR UPDATE;
  IF a IS NULL OR b IS NULL THEN RAISE EXCEPTION 'SCHEDULE_NOT_FOUND'; END IF;
  -- Compare the requested shifts with current data before applying an old request.
  IF lower(split_part(coalesce(a->s.from_day->>'shift',a->>s.from_day,''),'_',1))<>lower(s.from_shift)
    OR lower(split_part(coalesce(b->s.to_day->>'shift',b->>s.to_day,''),'_',1))<>lower(s.to_shift) THEN
    RAISE EXCEPTION 'CONFLICT: requested shifts changed' USING ERRCODE='40001';
  END IF;
  a_new:=jsonb_set(a,ARRAY[s.from_day],coalesce(b->s.from_day,'""'::jsonb),true);
  b_new:=jsonb_set(b,ARRAY[s.from_day],coalesce(a->s.from_day,'""'::jsonb),true);
  IF s.from_day<>s.to_day THEN
    a_new:=jsonb_set(a_new,ARRAY[s.to_day],coalesce(b->s.to_day,'""'::jsonb),true);
    b_new:=jsonb_set(b_new,ARRAY[s.to_day],coalesce(a->s.to_day,'""'::jsonb),true);
  END IF;
  PERFORM public.save_employee_schedule(s.week_date,s.from_emp_id,a_new,av);
  PERFORM public.save_employee_schedule(s.week_date,s.to_emp_id,b_new,bv);
    NEW.resolved_at:=now();
  END IF;
  RETURN NEW;
END;
$$;
DROP TRIGGER IF EXISTS stability_swap_transition ON public.shift_swaps;
CREATE TRIGGER stability_swap_transition BEFORE UPDATE ON public.shift_swaps
  FOR EACH ROW EXECUTE FUNCTION public.guard_swap_transition();

CREATE OR REPLACE FUNCTION public.jev_approve_swap(
  p_swap_id uuid, p_snapshot jsonb, p_risk numeric, p_noul numeric, p_confidence numeric, p_model text
) RETURNS boolean LANGUAGE plpgsql SECURITY INVOKER SET search_path=public AS $$
DECLARE s public.shift_swaps%ROWTYPE; config public.jev_auto_approval_settings%ROWTYPE;
  r record; actual integer; actual_shifts jsonb; staff jsonb;
BEGIN
  IF current_user <> 'service_role' THEN RAISE EXCEPTION 'PERMISSION_DENIED'; END IF;
  SELECT * INTO s FROM public.shift_swaps WHERE id=p_swap_id FOR UPDATE;
  IF NOT FOUND OR s.status <> 'pending_manager' THEN RETURN false; END IF;
  SELECT * INTO config FROM public.jev_auto_approval_settings WHERE store_id=s.store FOR SHARE;
  IF NOT FOUND OR NOT config.enabled OR p_model IS DISTINCT FROM config.model
    OR p_risk IS NULL OR p_risk NOT BETWEEN 0 AND 60
    OR p_noul IS NULL OR p_noul NOT BETWEEN config.min_noul AND 1
    OR p_confidence IS NULL OR p_confidence NOT BETWEEN config.min_confidence AND 1 THEN RETURN false; END IF;
  IF p_snapshot->'versions'->s.week_date->>s.from_emp_id IS NULL
    OR p_snapshot->'versions'->s.week_date->>s.to_emp_id IS NULL THEN RETURN false; END IF;
  -- Very short commit section: also blocks INSERT of previously absent context rows.
  -- Model/network work always happens BEFORE this transaction.
  LOCK TABLE public.schedules IN SHARE ROW EXCLUSIVE MODE;
  PERFORM 1 FROM public.employees WHERE id IN (s.from_emp_id,s.to_emp_id) ORDER BY id FOR SHARE;
  SELECT jsonb_agg(jsonb_build_object('id',id,'type',type,'dept',dept,'max_h',max_h,'is_active',is_active) ORDER BY id)
    INTO staff FROM public.employees WHERE id IN (s.from_emp_id,s.to_emp_id);
  IF staff IS DISTINCT FROM p_snapshot->'employees' THEN RETURN false; END IF;
  FOR r IN SELECT w.key AS week, e.key AS emp, e.value::integer AS version
    FROM jsonb_each(p_snapshot->'versions') w CROSS JOIN LATERAL jsonb_each_text(w.value) e ORDER BY w.key,e.key LOOP
    SELECT version,shifts INTO actual,actual_shifts FROM public.schedules WHERE week_date=r.week AND emp_id=r.emp FOR UPDATE;
    IF coalesce(actual,0)<>r.version THEN RETURN false; END IF;
    -- Also catch legacy/direct writes that did not increment version.
    IF actual_shifts IS DISTINCT FROM p_snapshot->'shifts'->r.week->r.emp THEN RETURN false; END IF;
  END LOOP;
  PERFORM public.approve_shift_swap_atomic_v2(s.id,'Jev: tự duyệt sau kiểm tra rule và phiên bản lịch');
  INSERT INTO public.jev_decisions(task,ok,model,answers,auto_approved)
    VALUES('shift_swap_commit',true,p_model,jsonb_build_object('swap_id',s.id,'risk_level',p_risk,'noul',p_noul),true);
  RETURN true;
END;
$$;
REVOKE ALL ON FUNCTION public.jev_approve_swap(uuid,jsonb,numeric,numeric,numeric,text) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.jev_approve_swap(uuid,jsonb,numeric,numeric,numeric,text),
  public.approve_shift_swap_atomic_v2(uuid,text), public.save_employee_schedule(text,text,jsonb,integer) TO service_role;

ALTER TABLE public.shelf_items ADD COLUMN IF NOT EXISTS expiry_time time;
ALTER TABLE public.shelf_items ADD COLUMN IF NOT EXISTS expiry_time_2 time;
ALTER TABLE public.shelf_items ADD COLUMN IF NOT EXISTS average_sales_per_hour numeric CHECK (average_sales_per_hour >= 0);
ALTER TABLE public.shelf_items ADD COLUMN IF NOT EXISTS triage_policy jsonb NOT NULL DEFAULT '{}'::jsonb;

-- Replace a shelf atomically and preserve hour-level expiry data.
CREATE OR REPLACE FUNCTION public.replace_shelf_items_atomic(
  p_shelf_id uuid, p_store_id text, p_items jsonb, p_updated_by text
) RETURNS SETOF public.shelf_items LANGUAGE plpgsql SECURITY INVOKER SET search_path=public AS $$
BEGIN
  IF auth.uid() IS NULL THEN RAISE EXCEPTION 'AUTH_REQUIRED'; END IF;
  PERFORM pg_advisory_xact_lock(hashtextextended('shelf:'||p_shelf_id::text,0));
  PERFORM 1 FROM public.store_shelves WHERE id=p_shelf_id AND store_id=p_store_id
    AND (public.can_manage_store(store_id) OR public.current_emp_id()=ANY(string_to_array(assignee_id,',')));
  IF NOT FOUND THEN RAISE EXCEPTION 'SHELF_NOT_FOUND'; END IF;
  IF jsonb_typeof(p_items) IS DISTINCT FROM 'array' THEN RAISE EXCEPTION 'INVALID_ITEMS'; END IF;
  DELETE FROM public.shelf_items WHERE shelf_id=p_shelf_id;
  RETURN QUERY INSERT INTO public.shelf_items(shelf_id,store_id,product_name,sku,qty,expiry_date,expiry_date_2,
    expiry_time,expiry_time_2,average_sales_per_hour,triage_policy,note,updated_by)
  SELECT p_shelf_id,p_store_id,r.product_name,r.sku,r.qty,r.expiry_date,r.expiry_date_2,r.expiry_time,r.expiry_time_2,
    r.average_sales_per_hour,coalesce(r.triage_policy,'{}'::jsonb),r.note,public.current_emp_id()
  FROM jsonb_to_recordset(p_items) AS r(product_name text,sku text,qty numeric,expiry_date date,expiry_date_2 date,
    expiry_time time,expiry_time_2 time,average_sales_per_hour numeric,triage_policy jsonb,note text) RETURNING *;
END;
$$;
REVOKE ALL ON FUNCTION public.replace_shelf_items_atomic(uuid,text,jsonb,text) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.replace_shelf_items_atomic(uuid,text,jsonb,text) TO authenticated;

-- SOURCE: 20260927000000_password_reset_otps.sql
-- SHA256: 5a103be51e00ebad4ec0bb36a0e268a69567222393ed0e1e5384d471a8252c2f
-- OTP recovery: admin -> Telegram; employees -> registered recovery email.

-- Fresh databases may not have the legacy admin log table yet.
CREATE TABLE IF NOT EXISTS public.admin_logs (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(), actor_id text, actor_name text,
  action text NOT NULL, target text, detail text, created_at timestamptz DEFAULT now()
);
ALTER TABLE public.admin_logs ENABLE ROW LEVEL SECURITY;
GRANT SELECT,INSERT ON public.admin_logs TO service_role;
GRANT SELECT ON public.admin_logs TO authenticated;
DROP POLICY IF EXISTS password_recovery_admin_log_read ON public.admin_logs;
CREATE POLICY password_recovery_admin_log_read ON public.admin_logs FOR SELECT TO authenticated USING (public.is_admin());
ALTER TABLE public.employees ADD COLUMN IF NOT EXISTS recovery_email text;
ALTER TABLE public.employees ADD COLUMN IF NOT EXISTS password_changed_at timestamptz;
ALTER TABLE public.employees ADD COLUMN IF NOT EXISTS password_deadline timestamptz;
ALTER TABLE public.employees DROP CONSTRAINT IF EXISTS employees_recovery_email_valid;
ALTER TABLE public.employees ADD CONSTRAINT employees_recovery_email_valid
  CHECK (recovery_email IS NULL OR (length(recovery_email)<=254 AND recovery_email ~ '^[^[:space:]@]+@[^[:space:]@]+\.[^[:space:]@]+$'));

CREATE OR REPLACE FUNCTION public.guard_recovery_email() RETURNS trigger
LANGUAGE plpgsql SECURITY INVOKER SET search_path=public,pg_temp AS $$
BEGIN
  IF TG_OP='UPDATE' AND NEW.recovery_email IS NOT DISTINCT FROM OLD.recovery_email THEN RETURN NEW; END IF;
  IF NEW.recovery_email IS NULL AND TG_OP='INSERT' THEN RETURN NEW; END IF;
  IF current_user IN ('authenticated','anon') THEN
    IF NOT (public.is_admin() OR
      (public.has_role('AREA_MANAGER') AND EXISTS(SELECT 1 FROM unnest(string_to_array(NEW.dept,',')) d WHERE trim(d) IN (SELECT public.my_managed_stores()))) OR
      (public.has_role('STORE_MANAGER') AND EXISTS(SELECT 1 FROM unnest(string_to_array(NEW.dept,',')) d WHERE trim(d) IN (SELECT public.my_managed_stores()))
        AND NOT (upper(coalesce(NEW.role,'')) = ANY(ARRAY['ADMIN','OFC','AM','AREA_MANAGER','SM','STORE_MANAGER'])
          OR upper(coalesce(NEW.type,'')) = ANY(ARRAY['ADMIN','OFC','AM','AREA_MANAGER','SM','STORE_MANAGER'])
          OR upper(coalesce(NEW.job_title,'')) = ANY(ARRAY['ADMIN','OFC','AM','AREA_MANAGER','SM','STORE_MANAGER'])
          OR concat_ws(' ',NEW.role,NEW.job_title) ILIKE ANY(ARRAY['%quản lý%','%cửa hàng trưởng%','%khu vực%'])))) THEN
      RAISE EXCEPTION 'RECOVERY_EMAIL_REQUIRES_MANAGER';
    END IF;
  END IF;
  NEW.recovery_email := nullif(lower(trim(NEW.recovery_email)),'');
  RETURN NEW;
END $$;
DROP TRIGGER IF EXISTS employee_recovery_email_guard ON public.employees;
CREATE TRIGGER employee_recovery_email_guard BEFORE INSERT OR UPDATE ON public.employees
FOR EACH ROW EXECUTE FUNCTION public.guard_recovery_email();

CREATE TABLE IF NOT EXISTS public.password_reset_otps (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  emp_id text NOT NULL UNIQUE,
  otp_code text NOT NULL CHECK (otp_code ~ '^[0-9a-f]{64}$'),
  expires_at timestamptz NOT NULL DEFAULT now() + interval '5 minutes',
  attempts int NOT NULL DEFAULT 0 CHECK (attempts BETWEEN 0 AND 5),
  created_at timestamptz NOT NULL DEFAULT now(),
  delivery_address text
);
-- Separate history preserves the limit after OTP deletion; no OTP/password stored here.
CREATE TABLE IF NOT EXISTS public.password_reset_otp_requests (
  id uuid PRIMARY KEY, emp_id text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(), claimed_at timestamptz,
  status text NOT NULL DEFAULT 'requested' CHECK (status IN ('requested','processing','completed','failed'))
);
CREATE INDEX IF NOT EXISTS password_reset_requests_employee_time ON public.password_reset_otp_requests(emp_id,created_at DESC);
ALTER TABLE public.password_reset_otps ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.password_reset_otp_requests ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.password_reset_otps,public.password_reset_otp_requests FROM PUBLIC,anon,authenticated;
GRANT ALL ON public.password_reset_otps,public.password_reset_otp_requests TO service_role;

CREATE OR REPLACE FUNCTION public.issue_password_reset_otp(p_emp_id text,p_hash text)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=public,pg_temp AS $$
DECLARE v_id uuid:=gen_random_uuid(); v_name text; v_email text; v_active boolean; v_count int;
BEGIN
  PERFORM pg_advisory_xact_lock(hashtextextended('password-reset:'||p_emp_id,0));
  IF p_emp_id='admin' THEN v_name:='Quản trị viên';
  ELSE
    SELECT name,is_active,recovery_email INTO v_name,v_active,v_email FROM employees WHERE id=p_emp_id;
    IF NOT FOUND THEN RETURN jsonb_build_object('code','EMPLOYEE_NOT_FOUND'); END IF;
    IF NOT v_active THEN RETURN jsonb_build_object('code','EMPLOYEE_INACTIVE'); END IF;
    IF nullif(v_email,'') IS NULL THEN RETURN jsonb_build_object('code','RECOVERY_EMAIL_MISSING'); END IF;
  END IF;
  IF NOT EXISTS(SELECT 1 FROM auth.users WHERE email=p_emp_id||'@ofc.app') THEN RETURN jsonb_build_object('code','AUTH_ACCOUNT_MISSING'); END IF;
  IF EXISTS(SELECT 1 FROM password_reset_otp_requests WHERE emp_id=p_emp_id AND status='processing'
    AND claimed_at>now()-interval '5 minutes') THEN RETURN jsonb_build_object('code','RESET_IN_PROGRESS'); END IF;
  SELECT count(*) INTO v_count FROM password_reset_otp_requests WHERE emp_id=p_emp_id AND created_at>now()-interval '15 minutes';
  IF v_count>=3 THEN RETURN jsonb_build_object('code','RATE_LIMITED'); END IF;
  DELETE FROM password_reset_otp_requests WHERE created_at<now()-interval '1 day';
  DELETE FROM password_reset_otps WHERE emp_id=p_emp_id;
  INSERT INTO password_reset_otp_requests(id,emp_id) VALUES(v_id,p_emp_id);
  INSERT INTO password_reset_otps(id,emp_id,otp_code,delivery_address) VALUES(v_id,p_emp_id,p_hash,v_email);
  RETURN jsonb_build_object('code','OK','id',v_id,'name',v_name,'email',v_email);
END $$;

CREATE OR REPLACE FUNCTION public.claim_password_reset_otp(p_emp_id text,p_hash text)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=public,pg_temp AS $$
DECLARE v_otp password_reset_otps%ROWTYPE; v_uid uuid; v_status text; v_email text;
BEGIN
  PERFORM pg_advisory_xact_lock(hashtextextended('password-reset:'||p_emp_id,0));
  IF p_emp_id<>'admin' THEN
    SELECT recovery_email INTO v_email FROM employees WHERE id=p_emp_id AND is_active;
    IF NOT FOUND THEN RETURN jsonb_build_object('code','EMPLOYEE_INACTIVE'); END IF;
  END IF;
  SELECT * INTO v_otp FROM password_reset_otps WHERE emp_id=p_emp_id FOR UPDATE;
  IF NOT FOUND THEN RETURN jsonb_build_object('code','OTP_INVALID'); END IF;
  SELECT status INTO v_status FROM password_reset_otp_requests WHERE id=v_otp.id;
  IF v_status IS DISTINCT FROM 'requested' THEN RETURN jsonb_build_object('code','OTP_USED'); END IF;
  IF v_otp.expires_at<=now() THEN RETURN jsonb_build_object('code','OTP_EXPIRED'); END IF;
  IF v_otp.delivery_address IS DISTINCT FROM v_email THEN RETURN jsonb_build_object('code','OTP_EXPIRED'); END IF;
  IF v_otp.attempts>=5 THEN RETURN jsonb_build_object('code','OTP_LOCKED'); END IF;
  IF v_otp.otp_code IS DISTINCT FROM p_hash THEN
    UPDATE password_reset_otps SET attempts=attempts+1 WHERE id=v_otp.id;
    RETURN jsonb_build_object('code',CASE WHEN v_otp.attempts=4 THEN 'OTP_LOCKED' ELSE 'OTP_INVALID' END);
  END IF;
  SELECT id INTO v_uid FROM auth.users WHERE email=p_emp_id||'@ofc.app';
  IF v_uid IS NULL THEN RETURN jsonb_build_object('code','AUTH_ACCOUNT_MISSING'); END IF;
  UPDATE password_reset_otp_requests SET status='processing',claimed_at=now() WHERE id=v_otp.id;
  RETURN jsonb_build_object('code','OK','id',v_otp.id,'user_id',v_uid);
END $$;

CREATE OR REPLACE FUNCTION public.finish_password_reset_otp(p_id uuid,p_success boolean)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=public,pg_temp AS $$
DECLARE v_request password_reset_otp_requests%ROWTYPE; v_emp_id text;
BEGIN
  SELECT emp_id INTO v_emp_id FROM password_reset_otp_requests WHERE id=p_id;
  IF NOT FOUND THEN RETURN jsonb_build_object('code','OTP_USED'); END IF;
  PERFORM pg_advisory_xact_lock(hashtextextended('password-reset:'||v_emp_id,0));
  SELECT * INTO v_request FROM password_reset_otp_requests WHERE id=p_id FOR UPDATE;
  IF v_request.status='completed' AND p_success THEN RETURN jsonb_build_object('code','OK'); END IF;
  IF p_success AND v_request.status<>'processing' THEN RETURN jsonb_build_object('code','OTP_USED'); END IF;
  IF p_success THEN
    UPDATE employees SET password_changed_at=now() WHERE id=v_request.emp_id;
    UPDATE app_profiles SET credential_set_at=now() WHERE emp_id=v_request.emp_id;
    INSERT INTO admin_logs(actor_id,actor_name,action,target,detail) VALUES(v_request.emp_id,v_request.emp_id,'PASSWORD_RESET_OTP',v_request.emp_id,
      'Tài khoản '||v_request.emp_id||' tự đặt lại mật khẩu bằng OTP.');
  END IF;
  DELETE FROM password_reset_otps WHERE id=p_id;
  UPDATE password_reset_otp_requests SET status=CASE WHEN p_success THEN 'completed' ELSE 'failed' END WHERE id=p_id;
  RETURN jsonb_build_object('code','OK');
END $$;
REVOKE ALL ON FUNCTION public.issue_password_reset_otp(text,text),public.claim_password_reset_otp(text,text),
  public.finish_password_reset_otp(uuid,boolean) FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.issue_password_reset_otp(text,text),public.claim_password_reset_otp(text,text),
  public.finish_password_reset_otp(uuid,boolean) TO service_role;
NOTIFY pgrst,'reload schema';

-- SOURCE: 20260928000000_legacy_schema_compat.sql
-- SHA256: 25e2b01afc4d74d19540ac1032acfe5706adc8268513f0f86c6a81970c8f6f00
-- Compatibility gaps observed on the production schema, 2026-09-28.
-- CREATE TABLE IF NOT EXISTS in the baseline does not add columns to old tables.
ALTER TABLE public.stores ADD COLUMN IF NOT EXISTS is_active boolean NOT NULL DEFAULT true;
ALTER TABLE public.stores ADD COLUMN IF NOT EXISTS demand jsonb;
ALTER TABLE public.store_shelves ADD COLUMN IF NOT EXISTS due_date date;
ALTER TABLE public.shelf_items ADD COLUMN IF NOT EXISTS sku text;
ALTER TABLE public.shelf_items ADD COLUMN IF NOT EXISTS expiry_date_2 date;
ALTER TABLE public.feedbacks ADD COLUMN IF NOT EXISTS emp_name text;
ALTER TABLE public.feedbacks ADD COLUMN IF NOT EXISTS emp_role text;
ALTER TABLE public.feedbacks ADD COLUMN IF NOT EXISTS emp_type text;
ALTER TABLE public.feedbacks ADD COLUMN IF NOT EXISTS note text;
ALTER TABLE public.feedbacks ADD COLUMN IF NOT EXISTS image_url text;
ALTER TABLE public.feedbacks ADD COLUMN IF NOT EXISTS resolution_note text;
-- Retain the name used by the currently published frontend during rollout.
ALTER TABLE public.feedbacks ADD COLUMN IF NOT EXISTS name text;
UPDATE public.feedbacks SET emp_name=name WHERE emp_name IS NULL AND name IS NOT NULL;
UPDATE public.feedbacks SET name=emp_name WHERE name IS NULL AND emp_name IS NOT NULL;
CREATE OR REPLACE FUNCTION public.sync_feedback_names() RETURNS trigger
LANGUAGE plpgsql SECURITY INVOKER SET search_path=public AS $$
BEGIN
  IF TG_OP='INSERT' THEN
    NEW.emp_name:=coalesce(NEW.emp_name,NEW.name,'');
    NEW.name:=NEW.emp_name;
  ELSIF NEW.emp_name IS DISTINCT FROM OLD.emp_name THEN
    NEW.name:=coalesce(NEW.emp_name,'');
  ELSIF NEW.name IS DISTINCT FROM OLD.name THEN
    NEW.emp_name:=NEW.name;
  END IF;
  RETURN NEW;
END;
$$;
DROP TRIGGER IF EXISTS feedback_names_compat ON public.feedbacks;
CREATE TRIGGER feedback_names_compat BEFORE INSERT OR UPDATE ON public.feedbacks
  FOR EACH ROW EXECUTE FUNCTION public.sync_feedback_names();

-- Live schedule_weeks.week_date is date; clean installations use ISO text.
-- Keep existing types/indexes/data instead of rewriting the table.
CREATE OR REPLACE FUNCTION public.is_week_editable(p_store_id text,p_week_date text)
RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path=public AS $$
  SELECT NOT EXISTS (SELECT 1 FROM public.schedule_weeks
    WHERE store_id=p_store_id AND week_date::text=p_week_date
      AND status NOT IN ('draft','rejected'));
$$;

-- These legacy credential RPCs are used by the app but were absent on clean installs.
CREATE OR REPLACE FUNCTION public.get_credential_state()
RETURNS TABLE(credential_set_at timestamptz,emp_id text)
LANGUAGE sql STABLE SECURITY DEFINER SET search_path=public AS $$
  SELECT p.credential_set_at,p.emp_id FROM public.app_profiles p
  WHERE p.id=auth.uid() AND p.emp_id=public.current_emp_id();
$$;
CREATE OR REPLACE FUNCTION public.mark_credential_set() RETURNS void
LANGUAGE sql SECURITY DEFINER SET search_path=public AS $$
  UPDATE public.app_profiles SET credential_set_at=now()
  WHERE id=auth.uid() AND emp_id=public.current_emp_id();
$$;
REVOKE ALL ON FUNCTION public.get_credential_state(),public.mark_credential_set() FROM PUBLIC,anon;
GRANT EXECUTE ON FUNCTION public.get_credential_state(),public.mark_credential_set() TO authenticated;
NOTIFY pgrst, 'reload schema';

-- Also runnable independently after deployment; checks metadata only, no employee PII.
DO $$
DECLARE signature text; table_name text; missing_columns text;
BEGIN
  FOREACH signature IN ARRAY ARRAY[
    'public.login_lookup_v2(text)', 'public.can_manage_store(text)',
    'public.ensure_app_profile_v2()', 'public.employee_is_manager(text,text,text)',
    'public.save_employee_schedule(text,text,jsonb,integer)',
    'public.upsert_schedules_bulk(jsonb)', 'public.approve_shift_swap_atomic_v2(uuid,text)',
    'public.resolve_feedback_atomic_v2(uuid,text,text,jsonb)',
    'public.replace_shelf_items_atomic(uuid,text,jsonb,text)',
    'public.get_credential_state()', 'public.mark_my_password_changed()',
    'public.issue_password_reset_otp(text,text)', 'public.claim_password_reset_otp(text,text)',
    'public.finish_password_reset_otp(uuid,boolean)'
  ] LOOP
    IF to_regprocedure(signature) IS NULL THEN RAISE EXCEPTION 'MISSING_RPC: %',signature; END IF;
  END LOOP;
  IF to_regprocedure('public.save_employee_schedule(text,text,jsonb)') IS NOT NULL THEN
    RAISE EXCEPTION 'OBSOLETE_SCHEDULE_OVERLOAD';
  END IF;
  FOREACH table_name IN ARRAY ARRAY['employees','schedules','schedule_weeks','feedbacks',
    'store_shelves','shelf_items','password_reset_otps','password_reset_otp_requests'] LOOP
    IF NOT (SELECT relrowsecurity FROM pg_class WHERE oid=to_regclass('public.'||table_name)) THEN
      RAISE EXCEPTION 'RLS_DISABLED: %',table_name;
    END IF;
  END LOOP;
  IF has_table_privilege('anon','public.password_reset_otps','SELECT')
    OR has_table_privilege('authenticated','public.password_reset_otps','SELECT')
    OR has_function_privilege('anon','public.claim_password_reset_otp(text,text)','EXECUTE')
    OR has_function_privilege('authenticated','public.issue_password_reset_otp(text,text)','EXECUTE') THEN
    RAISE EXCEPTION 'OTP_PRIVILEGES_TOO_BROAD';
  END IF;
  IF NOT has_function_privilege('anon','public.login_lookup_v2(text)','EXECUTE')
    OR NOT has_function_privilege('authenticated','public.save_employee_schedule(text,text,jsonb,integer)','EXECUTE') THEN
    RAISE EXCEPTION 'MISSING_CLIENT_RPC_GRANT';
  END IF;
  SELECT string_agg(required.tbl||'.'||required.col,', ') INTO missing_columns
  FROM (VALUES ('stores','is_active'),('stores','demand'),('store_shelves','due_date'),
    ('shelf_items','sku'),('shelf_items','expiry_date_2'),('feedbacks','emp_name'),
    ('feedbacks','emp_role'),('feedbacks','emp_type'),('feedbacks','note'),
    ('feedbacks','image_url'),('feedbacks','resolution_note'),('employees','recovery_email')) required(tbl,col)
  WHERE NOT EXISTS (SELECT 1 FROM information_schema.columns c
    WHERE c.table_schema='public' AND c.table_name=required.tbl AND c.column_name=required.col);
  IF missing_columns IS NOT NULL THEN RAISE EXCEPTION 'MISSING_COLUMNS: %',missing_columns; END IF;
END $$;
SELECT 'DATABASE_CHECKS_OK' AS result;

COMMIT;
SELECT 'DATABASE_CATCHUP_OK' AS result;
